"use client";

import { useEffect, useState } from "react";
import { findPatientByContact, createVisitByStaff, getDoctor, linkPatientFirebaseUid } from "@/lib/db";
import { createPatientFirebaseAccount } from "@/lib/patientAdmin";
import { normalizeContact, isValidContact } from "@/lib/phone";
import PatientRegistrationForm from "@/components/PatientRegistrationForm";
import VisitForm from "@/components/VisitForm";

// Doctor/registration-desk walk-in workflow:
//   search by mobile -> existing patient? use it : register a new one -> book a visit
//     -> queue token generated by the trusted backend (create_visit_by_staff RPC)
// Reuses PatientRegistrationForm (create step) and a generalized VisitForm (book
// step) instead of duplicating either. `doctorId` is the clinic to book visits
// against (the doctor's own id, or a registration desk's own doctor_id) -- passed
// straight through to createVisitByStaff, which re-validates it server-side
// regardless of what's sent from here.
export default function PatientSearchAndRegister({ doctorId, onPatientRegistered, onVisitCreated, getPatientRecordHref }) {
  const [step, setStep] = useState("search"); // search | results | register | visit | success
  const [contact, setContact] = useState("");
  const [results, setResults] = useState(null);
  const [selectedPatient, setSelectedPatient] = useState(null);
  const [doctor, setDoctor] = useState(null);
  const [createdVisit, setCreatedVisit] = useState(null);
  const [error, setError] = useState("");
  const [searching, setSearching] = useState(false);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const d = await getDoctor(doctorId);
        if (!cancelled) setDoctor(d);
      } catch (err) {
        if (!cancelled) setError(err.message || "Failed to load clinic details.");
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [doctorId]);

  function resetToSearch() {
    setStep("search");
    setContact("");
    setResults(null);
    setSelectedPatient(null);
    setCreatedVisit(null);
    setError("");
  }

  async function handleSearch(e) {
    e.preventDefault();
    setError("");
    if (!isValidContact(contact)) {
      setError("Enter a valid 10-digit mobile number.");
      return;
    }
    setSearching(true);
    try {
      const found = await findPatientByContact(contact);
      setResults(found);
      setStep("results");
    } catch (err) {
      setError(err.message || "Search failed. Please try again.");
    } finally {
      setSearching(false);
    }
  }

  function handlePicked(patient) {
    setSelectedPatient(patient);
    setStep("visit");
  }

  function handleRegistered(patient) {
    onPatientRegistered?.(patient);
    setSelectedPatient({ ...patient, hasLogin: !!patient.firebaseUid });
    setStep("visit");
  }

  function handleVisitCreated(visit) {
    setCreatedVisit(visit);
    onVisitCreated?.(visit, selectedPatient);
    setStep("success");
  }

  return (
    <div className="space-y-5">
      {error && <p className="text-sm text-rejected-text">{error}</p>}

      {step === "search" && (
        <form onSubmit={handleSearch} className="space-y-3">
          <div>
            <label className="form-label" htmlFor="search-contact">Search by mobile number</label>
            <div className="flex gap-2">
              <input
                id="search-contact"
                className="form-input"
                maxLength={10}
                placeholder="10-digit mobile number"
                value={contact}
                onChange={(e) => setContact(e.target.value.replace(/\D/g, ""))}
              />
              <button type="submit" className="btn-primary shrink-0" disabled={searching}>
                {searching ? "Searching..." : "Search"}
              </button>
            </div>
            <p className="text-xs text-ink-3 mt-1">Search first to avoid creating a duplicate patient record.</p>
          </div>
        </form>
      )}

      {step === "results" && (
        <div className="space-y-4">
          {results.length > 0 ? (
            <div className="card divide-y divide-border overflow-hidden">
              {results.map((patient) => (
                <PatientResultRow key={patient.id} patient={patient} onSelect={() => handlePicked(patient)} onLinked={(updated) => setResults((prev) => prev.map((p) => (p.id === updated.id ? { ...p, hasLogin: true } : p)))} />
              ))}
            </div>
          ) : (
            <p className="text-sm text-ink-3">No patient found with this mobile number.</p>
          )}
          <div className="flex items-center gap-4">
            <button type="button" className="btn-outline" onClick={() => setStep("search")}>Search again</button>
            <button type="button" className="text-sm font-semibold text-primary" onClick={() => setStep("register")}>
              {results.length > 0 ? "Not them? Register a new patient" : "Register this as a new patient"}
            </button>
          </div>
        </div>
      )}

      {step === "register" && (
        <div className="space-y-4">
          <PatientRegistrationForm initialContact={contact} onRegistered={handleRegistered} />
          <button type="button" className="text-sm text-ink-2" onClick={() => setStep(results ? "results" : "search")}>← Back</button>
        </div>
      )}

      {step === "visit" && selectedPatient && (
        <div className="space-y-4">
          <div className="card p-4 flex items-center justify-between text-sm">
            <div>
              <div className="font-semibold text-ink">{selectedPatient.name}</div>
              <div className="text-ink-2">{selectedPatient.contact}{selectedPatient.age ? ` · ${selectedPatient.age} yrs` : ""}{selectedPatient.gender ? ` · ${selectedPatient.gender}` : ""}</div>
            </div>
            <button type="button" className="text-sm text-ink-2" onClick={resetToSearch}>Change patient</button>
          </div>
          {!doctor ? (
            <p className="text-sm text-ink-3">Loading clinic details...</p>
          ) : (
            <VisitForm patient={selectedPatient} doctor={doctor} onBook={createVisitByStaff} onSuccess={handleVisitCreated} />
          )}
        </div>
      )}

      {step === "success" && createdVisit && (
        <div className="card p-5 space-y-3 text-center">
          <p className="text-sm text-ink-2">Added to queue</p>
          <p className="text-3xl font-bold text-primary">#{createdVisit.queueNumber}</p>
          <p className="text-sm text-ink-2">{selectedPatient?.name} · {createdVisit.slot}</p>
          <div className="flex items-center justify-center gap-4 pt-2">
            <button type="button" className="btn-primary" onClick={resetToSearch}>Register another patient</button>
            {getPatientRecordHref && (
              <a href={getPatientRecordHref(selectedPatient.id)} className="text-sm font-semibold text-primary">View patient record</a>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

// Inline row for a search result: pick it for a visit, or (if it has no portal login
// yet) create one. Account creation goes through two steps -- a Netlify function that
// creates the Firebase account (lib/patientAdmin.js) then link_patient_firebase_uid
// (lib/db.js) to attach it -- and rolls the Firebase account back if the link fails,
// so a failed attempt never leaves an orphaned Firebase user with no patient record
// attached.
function PatientResultRow({ patient, onSelect, onLinked }) {
  const [linking, setLinking] = useState(false);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [linked, setLinked] = useState(patient.hasLogin);

  async function handleLink(e) {
    e.preventDefault();
    setError("");
    setLoading(true);
    let created;
    try {
      created = await createPatientFirebaseAccount({ name: patient.name, email, password });
      const updated = await linkPatientFirebaseUid(patient.id, created.uid);
      setLinked(true);
      setLinking(false);
      onLinked?.(updated);
    } catch (err) {
      if (created) {
        // Account creation succeeded but the link failed (e.g. race with another
        // link attempt) -- there's no client-side way to delete another user's
        // Firebase account, so this can leave an orphaned, never-linked account.
        // That's a same-shape tradeoff to app/register/page.js's own rollback path,
        // just without a delete endpoint for a non-self account; surfaced clearly
        // rather than silently swallowed.
        setError("Account created but linking failed. Please try again or contact support.");
      } else {
        setError(err.message || "Failed to create login. Please try again.");
      }
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="p-4">
      <div className="flex items-center justify-between gap-3">
        <div className="text-sm">
          <div className="font-semibold text-ink">{patient.name}</div>
          <div className="text-ink-2">{patient.contact} · {patient.age} yrs · {patient.gender}</div>
          <div className="text-xs mt-0.5">
            {linked ? <span className="text-completed-text">Has portal login</span> : <span className="text-ink-3">No portal login</span>}
          </div>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          {!linked && (
            <button type="button" className="btn-outline text-xs px-2 py-1" onClick={() => setLinking((v) => !v)}>
              {linking ? "Cancel" : "Create Login"}
            </button>
          )}
          <button type="button" className="btn-primary text-xs px-2 py-1" onClick={onSelect}>Select</button>
        </div>
      </div>
      {linking && (
        <form onSubmit={handleLink} className="flex flex-wrap items-center gap-2 mt-3">
          <input type="email" required placeholder="Patient's email" className="form-input" value={email} onChange={(e) => setEmail(e.target.value)} />
          <input type="text" required minLength={6} placeholder="Temporary password" className="form-input" value={password} onChange={(e) => setPassword(e.target.value)} />
          <button type="submit" className="btn-primary" disabled={loading}>{loading ? "Creating..." : "Create Login"}</button>
        </form>
      )}
      {error && <p className="text-xs text-rejected-text mt-2">{error}</p>}
    </div>
  );
}
